// ── DOCUMENT CATALOG ─────────────────────────────────────────────────────────
// All 100+ legal document definitions: id, category, name, icon, price

const DOCS=[
  {id:'affidavit',cat:'personal',name:'General Affidavit',icon:'📜',price:0,lawyer:1500,free:true},
  {id:'self_declaration',cat:'personal',name:'Self Declaration',icon:'📋',price:0,lawyer:800,free:true},
  {id:'character_cert',cat:'personal',name:'Character Certificate',icon:'⭐',price:0,lawyer:1000,free:true},
  {id:'name_change',cat:'personal',name:'Name Change Affidavit',icon:'✏️',price:99,lawyer:1500,free:false},
  {id:'address_proof',cat:'personal',name:'Address Proof Affidavit',icon:'🏘️',price:49,lawyer:1000,free:false},
  {id:'income_affidavit',cat:'personal',name:'Income Affidavit',icon:'💵',price:49,lawyer:1000,free:false},
  {id:'noc',cat:'personal',name:'No Objection Certificate',icon:'✅',price:79,lawyer:1500,free:false},
  {id:'auth_letter',cat:'personal',name:'Authorization Letter',icon:'📩',price:49,lawyer:1000,free:false},
  {id:'domicile_affidavit',cat:'personal',name:'Domicile / Residence Affidavit',icon:'🏡',price:79,lawyer:1500,free:false},
  {id:'dob_affidavit',cat:'personal',name:'Date of Birth Affidavit',icon:'📅',price:79,lawyer:1500,free:false},
  {id:'single_status',cat:'personal',name:'Single / Unmarried Certificate',icon:'💍',price:79,lawyer:1200,free:false},
  {id:'nationality_affidavit',cat:'personal',name:'Nationality Affidavit',icon:'🇮🇳',price:99,lawyer:2000,free:false},
  {id:'caste_affidavit',cat:'personal',name:'Caste / Category Affidavit',icon:'📌',price:79,lawyer:1500,free:false},
  {id:'ews_affidavit',cat:'personal',name:'EWS Income & Asset Certificate',icon:'📊',price:99,lawyer:1500,free:false},
  {id:'id_theft_affidavit',cat:'personal',name:'Lost / Stolen Document Affidavit',icon:'🔐',price:79,lawyer:1500,free:false},
  {id:'rent_agreement',cat:'property',name:'Rent / Tenancy Agreement',icon:'🏠',price:149,lawyer:3000,free:false},
  {id:'lease_agreement',cat:'property',name:'Commercial Lease Agreement',icon:'🔑',price:199,lawyer:5000,free:false},
  {id:'leave_license',cat:'property',name:'Leave and License Agreement',icon:'🗝️',price:199,lawyer:5000,free:false},
  {id:'property_sale',cat:'property',name:'Agreement to Sell — Property',icon:'🏗️',price:249,lawyer:8000,free:false},
  {id:'property_affidavit',cat:'property',name:'Property Ownership Affidavit',icon:'🏡',price:149,lawyer:2500,free:false},
  {id:'property_declaration',cat:'property',name:'Property Ownership Declaration',icon:'📜',price:149,lawyer:2500,free:false},
  {id:'possession_letter',cat:'property',name:'Possession Handover Letter',icon:'📬',price:149,lawyer:2000,free:false},
  {id:'rent_receipt',cat:'property',name:'House Rent Receipt',icon:'🧾',price:0,lawyer:500,free:true},
  {id:'tenant_verify',cat:'property',name:'Tenant Police Verification',icon:'🚔',price:79,lawyer:500,free:false},
  {id:'property_will',cat:'property',name:'Simple Will / Testament',icon:'📝',price:249,lawyer:8000,free:false},
  {id:'mutation_affidavit',cat:'property',name:'Property Mutation Affidavit',icon:'🏛️',price:149,lawyer:3000,free:false},
  {id:'encumbrance_cert',cat:'property',name:'No Encumbrance Declaration',icon:'📋',price:149,lawyer:2500,free:false},
  {id:'property_gift',cat:'property',name:'Gift Deed',icon:'🎁',price:249,lawyer:8000,free:false},
  {id:'society_noc',cat:'property',name:'Society / Association NOC',icon:'🏢',price:99,lawyer:2000,free:false},
  {id:'property_indemnity',cat:'property',name:'Property Indemnity Bond',icon:'🔒',price:199,lawyer:5000,free:false},
  {id:'loan_agreement',cat:'financial',name:'Loan Agreement',icon:'💰',price:199,lawyer:5000,free:false},
  {id:'promissory_note',cat:'financial',name:'Promissory Note',icon:'📝',price:149,lawyer:2500,free:false},
  {id:'payment_agreement',cat:'financial',name:'Payment Agreement',icon:'💳',price:149,lawyer:2500,free:false},
  {id:'debt_settlement',cat:'financial',name:'Debt Settlement Agreement',icon:'🤝',price:199,lawyer:5000,free:false},
  {id:'loan_repayment',cat:'financial',name:'Loan Repayment Schedule',icon:'🔄',price:199,lawyer:5000,free:false},
  {id:'installment_agreement',cat:'financial',name:'Installment Payment Agreement',icon:'📊',price:149,lawyer:2500,free:false},
  {id:'money_receipt',cat:'financial',name:'Money Receipt',icon:'🧾',price:0,lawyer:500,free:true},
  {id:'advance_receipt',cat:'financial',name:'Advance Payment Receipt',icon:'💵',price:49,lawyer:500,free:false},
  {id:'loan_acknowledgement',cat:'financial',name:'Loan Acknowledgement Letter',icon:'📨',price:79,lawyer:1000,free:false},
  {id:'surety_bond',cat:'financial',name:'Surety / Guarantee Bond',icon:'🛡️',price:199,lawyer:5000,free:false},
  {id:'indemnity_bond',cat:'financial',name:'Indemnity Bond',icon:'📌',price:149,lawyer:3000,free:false},
  {id:'mortgage_deed',cat:'financial',name:'Simple Mortgage Deed',icon:'🏦',price:249,lawyer:8000,free:false},
  {id:'cheque_bounce_notice',cat:'financial',name:'Cheque Bounce Notice (Sec 138)',icon:'⚡',price:149,lawyer:3000,free:false},
  {id:'financial_affidavit',cat:'financial',name:'Financial Status Affidavit',icon:'💼',price:99,lawyer:2000,free:false},
  {id:'bank_guarantee',cat:'financial',name:'Personal Bank Guarantee',icon:'🏛️',price:149,lawyer:3000,free:false},
  {id:'partnership_deed',cat:'business',name:'Partnership Deed',icon:'🏢',price:249,lawyer:10000,free:false},
  {id:'nda',cat:'business',name:'Non-Disclosure Agreement (NDA)',icon:'🔒',price:199,lawyer:5000,free:false},
  {id:'service_agreement',cat:'business',name:'Service Agreement',icon:'🛠️',price:199,lawyer:5000,free:false},
  {id:'vendor_agreement',cat:'business',name:'Vendor Supply Agreement',icon:'📦',price:199,lawyer:5000,free:false},
  {id:'freelance_contract',cat:'business',name:'Freelance / Consultant Contract',icon:'🖊️',price:149,lawyer:3000,free:false},
  {id:'partnership_dissolution',cat:'business',name:'Partnership Dissolution Deed',icon:'💔',price:249,lawyer:10000,free:false},
  {id:'vendor_payment',cat:'business',name:'Vendor Payment Agreement',icon:'💱',price:149,lawyer:3000,free:false},
  {id:'mou',cat:'business',name:'Memorandum of Understanding (MOU)',icon:'🤝',price:199,lawyer:6000,free:false},
  {id:'distributor_agreement',cat:'business',name:'Distributor / Dealer Agreement',icon:'🚚',price:199,lawyer:6000,free:false},
  {id:'agency_agreement',cat:'business',name:'Agency / Commission Agreement',icon:'🤜',price:199,lawyer:5000,free:false},
  {id:'sale_of_business',cat:'business',name:'Business / Shop Sale Agreement',icon:'🏪',price:249,lawyer:10000,free:false},
  {id:'business_dissolution',cat:'business',name:'Business Closure Notice',icon:'🔚',price:149,lawyer:3000,free:false},
  {id:'non_compete',cat:'business',name:'Non-Compete Agreement',icon:'🚫',price:199,lawyer:5000,free:false},
  {id:'intellectual_property',cat:'business',name:'IP / Copyright Assignment',icon:'©️',price:249,lawyer:8000,free:false},
  {id:'shareholder_agreement',cat:'business',name:'Shareholder Agreement',icon:'📈',price:299,lawyer:15000,free:false},
  {id:'joint_venture',cat:'business',name:'Joint Venture Agreement',icon:'🔗',price:299,lawyer:15000,free:false},
  {id:'software_license',cat:'business',name:'Software / SaaS License Agreement',icon:'💻',price:249,lawyer:8000,free:false},
  {id:'website_tnc',cat:'business',name:'Website Terms and Conditions',icon:'🌐',price:199,lawyer:5000,free:false},
  {id:'employment_contract',cat:'employment',name:'Employment Contract',icon:'💼',price:199,lawyer:5000,free:false},
  {id:'offer_letter',cat:'employment',name:'Employee Offer Letter',icon:'📬',price:149,lawyer:2500,free:false},
  {id:'appointment_letter',cat:'employment',name:'Appointment / Joining Letter',icon:'📄',price:99,lawyer:1500,free:false},
  {id:'resignation_acceptance',cat:'employment',name:'Resignation Acceptance Letter',icon:'👋',price:79,lawyer:1000,free:false},
  {id:'termination_letter',cat:'employment',name:'Employment Termination Letter',icon:'🛑',price:149,lawyer:3000,free:false},
  {id:'experience_cert',cat:'employment',name:'Experience Certificate',icon:'🏆',price:79,lawyer:1000,free:false},
  {id:'salary_certificate',cat:'employment',name:'Salary / Compensation Certificate',icon:'💰',price:79,lawyer:1000,free:false},
  {id:'hr_noc',cat:'employment',name:'HR No Objection Certificate',icon:'✅',price:79,lawyer:1000,free:false},
  {id:'internship_letter',cat:'employment',name:'Internship Offer Letter',icon:'🎓',price:79,lawyer:800,free:false},
  {id:'probation_extension',cat:'employment',name:'Probation Extension Letter',icon:'⏳',price:99,lawyer:1500,free:false},
  {id:'warning_letter',cat:'employment',name:'Employee Warning Letter',icon:'⚠️',price:99,lawyer:1500,free:false},
  {id:'relieving_letter',cat:'employment',name:'Relieving Letter',icon:'🚪',price:79,lawyer:1000,free:false},
  {id:'marriage_affidavit',cat:'family',name:'Marriage Affidavit',icon:'💍',price:99,lawyer:1500,free:false},
  {id:'family_declaration',cat:'family',name:'Family / Household Declaration',icon:'👨‍👩‍👧',price:79,lawyer:1000,free:false},
  {id:'guardianship_declaration',cat:'family',name:'Guardianship Declaration',icon:'🧒',price:149,lawyer:3000,free:false},
  {id:'guardianship_affidavit',cat:'family',name:'Guardianship Affidavit',icon:'👶',price:149,lawyer:3000,free:false},
  {id:'poa_general',cat:'family',name:'General Power of Attorney',icon:'✍️',price:249,lawyer:8000,free:false},
  {id:'poa_property',cat:'family',name:'Special POA for Property',icon:'🏠',price:249,lawyer:8000,free:false},
  {id:'divorce_mutual',cat:'family',name:'Mutual Divorce Agreement',icon:'⚖️',price:299,lawyer:15000,free:false},
  {id:'relinquishment_deed',cat:'family',name:'Relinquishment Deed',icon:'🤲',price:249,lawyer:8000,free:false},
  {id:'adoption_affidavit',cat:'family',name:'Child Adoption Declaration',icon:'❤️',price:149,lawyer:4000,free:false},
  {id:'nomination_letter',cat:'family',name:'Nominee Declaration Letter',icon:'📌',price:79,lawyer:1000,free:false},
  {id:'succession_cert',cat:'family',name:'Legal Heir / Succession Affidavit',icon:'👑',price:149,lawyer:3000,free:false},
  {id:'general_affidavit',cat:'court',name:'General Court Affidavit',icon:'⚖️',price:149,lawyer:3000,free:false},
  {id:'notary_affidavit',cat:'court',name:'Notary Affidavit',icon:'📃',price:149,lawyer:3000,free:false},
  {id:'court_declaration',cat:'court',name:'Court Declaration / Statement',icon:'🏛️',price:199,lawyer:5000,free:false},
  {id:'legal_undertaking',cat:'court',name:'Legal Undertaking',icon:'📌',price:199,lawyer:5000,free:false},
  {id:'legal_notice',cat:'court',name:'Legal Notice',icon:'⚡',price:199,lawyer:6000,free:false},
  {id:'bail_surety',cat:'court',name:'Bail Surety Bond',icon:'🔓',price:199,lawyer:5000,free:false},
  {id:'complaint_letter',cat:'court',name:'Police Complaint / FIR Letter',icon:'🚔',price:99,lawyer:2000,free:false},
  {id:'vakalat_letter',cat:'court',name:'Vakalatnama',icon:'👨‍⚖️',price:149,lawyer:2000,free:false},
  {id:'settlement_deed',cat:'court',name:'Out of Court Settlement Deed',icon:'🤝',price:249,lawyer:8000,free:false},
  {id:'stay_order_affidavit',cat:'court',name:'Affidavit for Stay Application',icon:'⏸️',price:199,lawyer:5000,free:false},
  {id:'gap_certificate',cat:'student',name:'Gap Certificate Affidavit',icon:'📅',price:0,lawyer:800,free:true},
  {id:'bonafide_declaration',cat:'student',name:'Bonafide Certificate / Declaration',icon:'🎓',price:49,lawyer:500,free:false},
  {id:'student_affidavit',cat:'student',name:'Student Affidavit',icon:'📚',price:49,lawyer:800,free:false},
  {id:'scholarship_affidavit',cat:'student',name:'Scholarship / Financial Need Affidavit',icon:'🏅',price:79,lawyer:1000,free:false},
  {id:'college_noc',cat:'student',name:'College / University NOC',icon:'✅',price:79,lawyer:1000,free:false},
  {id:'internship_consent',cat:'student',name:'Parent Consent for Internship',icon:'✈️',price:79,lawyer:1000,free:false},
  {id:'migration_certificate',cat:'student',name:'Migration / Transfer Affidavit',icon:'📦',price:79,lawyer:1000,free:false},
  {id:'exam_affidavit',cat:'student',name:'Exam / Exam Center Declaration',icon:'📝',price:49,lawyer:500,free:false},
  {id:'consumer_complaint',cat:'consumer',name:'Consumer Complaint Letter',icon:'📢',price:99,lawyer:2000,free:false},
  {id:'refund_demand',cat:'consumer',name:'Refund / Replacement Demand Notice',icon:'💸',price:79,lawyer:1500,free:false},
  {id:'deficiency_notice',cat:'consumer',name:'Deficiency of Service Notice',icon:'⚠️',price:99,lawyer:2000,free:false},
  {id:'online_fraud_complaint',cat:'consumer',name:'Online Fraud Complaint',icon:'🛡️',price:99,lawyer:2000,free:false},
  {id:'insurance_claim',cat:'consumer',name:'Insurance Claim Letter',icon:'📋',price:99,lawyer:2000,free:false},
  {id:'warranty_claim',cat:'consumer',name:'Warranty / Product Defect Claim',icon:'🔧',price:79,lawyer:1500,free:false},
  {id:'medical_negligence',cat:'consumer',name:'Medical Negligence Complaint',icon:'🏥',price:149,lawyer:4000,free:false},
];
